### ISSUE TITLE
Release and compiling

### ISSUE THREAD

**Issue by SzotsGabor** [mwyngaarden/Cadie#1]
Hello Martin,

I am not sure if you wanted to release Cadie because I don't find it in "Releases". Until it is there I am not going to test it, I don't know if that is fine with you.

Another problem is that I can't compile it. An excerpt from the error messages:

In file included from pos.h:10,
                 from bench.h:8,
                 from bench.cpp:10:
move.h:26:24: error: 'popcount' is not a member of 'std'; did you mean 'count'?
   26 |     static_assert(std::popcount(PromoQFlag) == 1);
      |                        ^~~~~~~~
      |                        count
In file included from eval.h:5,
                 from tt.h:7,
                 from bench.cpp:13:
htable.h:19:24: error: 'popcount' is not a member of 'std'; did you mean 'count'?
   19 |     static_assert(std::popcount(Bytes) == 1);
      |                        ^~~~~~~~
      |                        count
htable.h:20:24: error: 'popcount' is not a member of 'std'; did you mean 'count'?
   20 |     static_assert(std::popcount(Count) == 1);
      |                        ^~~~~~~~
      |                        count

Cany you help there? I am not a programmer, it is tough for me to correct that. I am on Windows 10, using gcc.

Gabor Szots
CCRL testing group

**Comment by mwyngaarden** [comment]
Cadie is available to anyone and everyone for any purpose. I suppose it would just make the most sense to use the date of the last commit as the version since I do not have a release schedule. 

Are you attempting to build with simply running the make command? std::popcount is a C++20 feature so I should probably update the readme file to reflect that a C++20 compiler is required to build.

**Comment by SzotsGabor** [comment]
The problem is that unless you provide executables for Windows the public won't be able to use it because most of them are not programmers.

I tried to build it by running 'mingw32-make.exe' but I got this:
"FIND: Parameter format not correct
Input file specified two times.


../src/bench.cpp:14: *** missing separator.  Stop.
"

And I have just tried this: g++ *.cpp -std=c++20 -O3 -march=native -flto -oCadie_1.4-x64-SzG.exe
and I got this:
"mem.cpp: In function 'void* my_alloc(size_t)':
mem.cpp:30:14: error: 'aligned_alloc' is not a member of 'std'
   30 |     p = std::aligned_alloc(alignment, size);
      |              ^~~~~~~~~~~~~
"

**Comment by mwyngaarden** [comment]
I put some compiles together for Graham earlier this week when I incremented the version to 1.4. I'll see about putting something official up here today.

**Comment by tissatussa** [comment]
on Linux i have no problems with compilation : the `uci` command says v1.3 and it runs fine in CuteChess.

i discovered Cadie by the link to "Keele v1.0" from the CCRL list .. is Keele the predecessor ? Does Cadie v1.3 also have a CCRL rating of 2659 ?

**Comment by mwyngaarden** [comment]
Cadie 1.3 is also rated at CCRL, and about 200 Elo over Keele 1.0.  Yes, Keele is Cadie's predecessor. Move generation and evaluation is almost identical, but the search in Cadie is vastly improved.

**Comment by mwyngaarden** [comment]
Windows release builds now included.
