### ISSUE TITLE
v1.7 compile error on Linux : solved

### ISSUE THREAD

**Issue by tissatussa** [mwyngaarden/Cadie#2]
i was able to compile your v1.7 source on Linux, but only after changing 1 thing .. at first i got this error:

```
uci.cpp: In function ‘void uci_go(const std::string&)’:
uci.cpp:219:36: error: no matching function for call to ‘max(i64, long long int)’
  219 |         slimits.movetime = std::max(slimits.movetime - i64(MoveOverhead), 1ll);
      |                            ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

i changed the second parameter `1ll` into `i64(1)` to make it work, but i'm not a C++ programmer, so maybe a better solution exists ..

the resulting binary runs fine in CuteChess.

[ i'm on Xubuntu 22.04 ]

**Comment by mwyngaarden** [comment]
I made the mistake of fixing that line to compile with msvc and then not retesting on Ubuntu with g++. Thanks for the report.
